apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: nats-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: nats-poc-producer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_URL
              value: "nats://nats.nats-poc.svc.cluster.local:4222"
            - name: STREAM_NAME
              value: "AUTO_ORDERS"
            - name: RATE
              value: "100"
            - name: ACCOUNTS
              value: "10"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
